[package]
name = "cpython_rust_test"
version = "0.1.0"
edition = "2021"
authors = ["Oskar Meyenburg"]

[lib]
name = "test_library"
crate-type = ["cdylib"]

[dependencies.cpython]
version = "0.7.1"
features = ["extension-module"]
